In [1]:
import os
import duckdb

duckdb_path = os.getenv("DUCKDB_PATH")
assert duckdb_path is not None, "Variable 'DUCKDB_PATH' must be defined"

con = duckdb.connect(duckdb_path)
con.sql("SELECT * FROM INFORMATION_SCHEMA.TABLES;").df()

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action,TABLE_COMMENT
0,legislative,main,deputados,BASE TABLE,None,None,None,None,None,YES,NO,None,None
1,legislative,main,proposicoesTemas,BASE TABLE,None,None,None,None,None,YES,NO,None,None
2,legislative,main,votacoesObjetos,BASE TABLE,None,None,None,None,None,YES,NO,None,None
3,legislative,main,votacoesVotos,BASE TABLE,None,None,None,None,None,YES,NO,None,None
4,legislative,main,deputies_propositions,VIEW,None,None,None,None,None,NO,NO,None,None

In [7]:
most_voted_themes_query = open("../queries/most_voted_themes.sql").read()

most_voted_themes = con.execute(most_voted_themes_query).df()

most_voted_themes

    codTema                                         tema  total_votacoes
0        57                           Defesa e Segurança             216
1        46                                     Educação             185
2        44                  Direitos Humanos e Minorias             164
3        34                        Administração Pública             151
4        56                                        Saúde             143
5        70                Finanças Públicas e Orçamento             134
6        43             Direito Penal e Processual Penal             116
7        58                           Trabalho e Emprego              89
8        40                                     Economia              62
9        48  Meio Ambiente e Desenvolvimento Sustentável              50
10       51                          Estrutura Fundiária              50
11       61              Viação, Transporte e Mobilidade              47
12       66               Indústria, Comércio e Serviços              45
13       42             Direito Civil e Processual Civil              37
14       41             Cidades e Desenvolvimento Urbano              31
15       67               Direito e Defesa do Consumidor              31
16       52             Previdência e Assistência Social              28
17       54        Energia, Recursos Hídricos e Minerais              26
18       37                                 Comunicações              25
19       64  Agricultura, Pecuária, Pesca e Extrativismo              23
20       72             Homenagens e Datas Comemorativas              19
21       39                              Esporte e Lazer              17
22       76                            Direito e Justiça              12
23       53   Processo Legislativo e Atuação Parlamentar              10
24       60                                      Turismo               9
25       55  Relações Internacionais e Comércio Exterior               6
26       35                     Arte, Cultura e Religião               3
27       62               Ciência, Tecnologia e Inovação               2
28       68                       Direito Constitucional               1
29       86                   Ciências Sociais e Humanas               0
30       74                Política, Partidos e Eleições               0
31       85                   Ciências Exatas e da Terra               0

In [25]:
deputy_count_per_theme_query = open("../queries/deputy_count_per_theme.sql").read()

deputy_count_per_theme = con.execute(deputy_count_per_theme_query).df()

deputy_count_per_theme

    codTema                                         tema  total_deputados
0        70                Finanças Públicas e Orçamento              582
1        34                        Administração Pública              580
2        40                                     Economia              563
3        51                          Estrutura Fundiária              549
4        48  Meio Ambiente e Desenvolvimento Sustentável              530
5        56                                        Saúde              526
6        66               Indústria, Comércio e Serviços              516
7        58                           Trabalho e Emprego              498
8        67               Direito e Defesa do Consumidor              493
9        44                  Direitos Humanos e Minorias              493
10       54        Energia, Recursos Hídricos e Minerais              493
11       64  Agricultura, Pecuária, Pesca e Extrativismo              482
12       42             Direito Civil e Processual Civil              470
13       46                                     Educação              465
14       52             Previdência e Assistência Social              449
15       53   Processo Legislativo e Atuação Parlamentar              413
16       72             Homenagens e Datas Comemorativas              406
17       61              Viação, Transporte e Mobilidade              352
18       41             Cidades e Desenvolvimento Urbano              352
19       68                       Direito Constitucional                0
20       37                                 Comunicações                0
21       76                            Direito e Justiça                0
22       35                     Arte, Cultura e Religião                0
23       62               Ciência, Tecnologia e Inovação                0
24       60                                      Turismo                0
25       86                   Ciências Sociais e Humanas                0
26       85                   Ciências Exatas e da Terra                0
27       74                Política, Partidos e Eleições                0
28       43             Direito Penal e Processual Penal                0
29       55  Relações Internacionais e Comércio Exterior                0
30       39                              Esporte e Lazer                0
31       57                           Defesa e Segurança                0